services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf:/etc/mysql/conf.d
      - ./setup_master.sh:/docker-entrypoint-initdb.d/setup_master.sh
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin='mysql-bin-1' --binlog-format=ROW --gtid_mode=ON --enforce-gtid-consistency=ON
    networks:
      - mysql_net

  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/conf:/etc/mysql/conf.d
      - ./setup_slave.sh:/docker-entrypoint-initdb.d/setup_slave.sh
    depends_on:
      - mysql_master
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --relay-log='mysql-relay-bin' --log-bin='mysql-bin-2' --read-only=1
    networks:
      - mysql_net

  phpmyadmin_master:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_master
    environment:
      PMA_HOST: mysql_master
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql_master
    networks:
      - mysql_net

  phpmyadmin_slave:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_slave
    environment:
      PMA_HOST: mysql_slave
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql_slave
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge

